In [ ]:
import pandas as pd
dataframe1 = pd.read_csv("mainnn.csv")

In [ ]:
dataframe1

statement  depression_level
0                                i didnt feel humiliated                 2
1      i can go from feeling so hopeless to so damned...                 2
2       im grabbing a minute to post i feel greedy wrong                 4
3      i am ever feeling nostalgic about the fireplac...                 0
4                                   i am feeling grouchy                 4
...                                                  ...               ...
19995  im having ssa examination tomorrow in the morn...                 2
19996  i constantly worry about their fight against n...                 0
19997  i feel its important to share this info for th...                 0
19998  i truly feel that if you are passionate enough...                 0
19999  i feel like i just wanna buy any cute make up ...                 0

[20000 rows x 2 columns]

In [ ]:
def tolower(string):
  string = string.lower() 
  return string
dataframe1['statement']=dataframe1['statement'].apply(lambda sent : tolower(sent))

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stopper = set(stopwords.words("english"))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
stopper

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [ ]:
def removestop(sent):
  result = " "
  for i in sent.split():
    if i not in stopper:
      result=result+i+" "
  return result.strip()

dataframe1['statement'] = dataframe1['statement'].apply(lambda sent:removestop(sent))

In [ ]:
dataframe1

statement  depression_level
0                                  didnt feel humiliated                 2
1      go feeling hopeless damned hopeful around some...                 2
2              im grabbing minute post feel greedy wrong                 4
3      ever feeling nostalgic fireplace know still pr...                 0
4                                        feeling grouchy                 4
...                                                  ...               ...
19995  im ssa examination tomorrow morning im quite w...                 2
19996  constantly worry fight nature push limits inne...                 0
19997         feel important share info experience thing                 0
19998  truly feel passionate enough something stay tr...                 0
19999  feel like wanna buy cute make see online even one                 0

[20000 rows x 2 columns]

In [ ]:
import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   U

True

In [ ]:
lemmatizer = nltk.stem.WordNetLemmatizer()
def lemmatize1(sent):
  new_sent = ""
  for i in sent.split(" "):
    new_sent = new_sent+lemmatizer.lemmatize(i)+" "
  return new_sent
dataframe1['statement'] = dataframe1['statement'].apply(lambda sent:lemmatize1(sent))

In [ ]:
dataframe1

statement  depression_level
0                                 didnt feel humiliated                  2
1      go feeling hopeless damned hopeful around some...                 2
2             im grabbing minute post feel greedy wrong                  4
3      ever feeling nostalgic fireplace know still pr...                 0
4                                       feeling grouchy                  4
...                                                  ...               ...
19995  im ssa examination tomorrow morning im quite w...                 2
19996  constantly worry fight nature push limit inner...                 0
19997        feel important share info experience thing                  0
19998  truly feel passionate enough something stay tr...                 0
19999  feel like wanna buy cute make see online even ...                 0

[20000 rows x 2 columns]

In [ ]:
from keras.utils import np_utils
encoded_labels = np_utils.to_categorical(dataframe1['depression_level'])
encoded_labels.shape


(20000, 5)

In [ ]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(dataframe1['statement'],encoded_labels, test_size=0.4)

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
train_x_rep = [one_hot(w,5000) for w in train_x] #5000- vocabulary size
test_x_rep = [one_hot(w,5000) for w in test_x]

In [ ]:
train_y

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
sent_length = 40
embedded_train_x = pad_sequences(train_x_rep,padding='pre',maxlen=sent_length)
embedded_test_x = pad_sequences(test_x_rep,padding='pre',maxlen=sent_length)

In [ ]:
embedded_test_x

array([[   0,    0,    0, ..., 4142,  439, 1833],
       [   0,    0,    0, ..., 4171, 4130, 2332],
       [   0,    0,    0, ...,  700, 4171,  957],
       ...,
       [   0,    0,    0, ..., 3482,  228, 3362],
       [   0,    0,    0, ..., 4834, 4525, 2333],
       [   0,    0,    0, ..., 2693, 4869,  822]], dtype=int32)

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Bidirectional
from tensorflow.keras.layers import Dropout,Flatten

In [ ]:
embed_vect = 40
model = Sequential()
model.add(Embedding(5000,embed_vect,input_length=40))
model.add(Dropout(0.3))
model.add(Bidirectional(LSTM(150)))
model.add(Dropout(0.3))
model.add(Dense(5,activation='sigmoid'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics='accuracy')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 40, 40)            0         
                                                                 
 bidirectional (Bidirectiona  (None, 300)              229200    
 l)                                                              
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense (Dense)               (None, 5)                 1505      
                                                                 
Total params: 430,705
Trainable params: 430,705
Non-trainable params: 0
__________________________________________________

In [ ]:
embedded_test_x.shape, test_y.shape, embedded_train_x.shape, train_y.shape

((8000, 40), (8000, 5), (12000, 40), (12000, 5))

In [ ]:
model.fit(embedded_train_x,train_y,epochs=10,batch_size=128,validation_data=(embedded_test_x,test_y))

Epoch 1/10
94/94 [==============================] - 45s 428ms/step - loss: 1.3791 - accuracy: 0.4226 - val_loss: 1.3310 - val_accuracy: 0.4181
Epoch 2/10
94/94 [==============================] - 37s 389ms/step - loss: 1.0944 - accuracy: 0.5711 - val_loss: 0.8686 - val_accuracy: 0.6874
Epoch 3/10
94/94 [==============================] - 36s 387ms/step - loss: 0.6523 - accuracy: 0.7612 - val_loss: 0.6847 - val_accuracy: 0.7594
Epoch 4/10
94/94 [==============================] - 40s 424ms/step - loss: 0.4823 - accuracy: 0.8298 - val_loss: 0.5898 - val_accuracy: 0.7941
Epoch 5/10
94/94 [==============================] - 40s 422ms/step - loss: 0.3506 - accuracy: 0.8827 - val_loss: 0.5114 - val_accuracy: 0.8314
Epoch 6/10
94/94 [==============================] - 40s 424ms/step - loss: 0.2524 - accuracy: 0.9178 - val_loss: 0.4557 - val_accuracy: 0.8508
Epoch 7/10
94/94 [==============================] - 40s 423ms/step - loss: 0.1983 - accuracy: 0.9348 - val_loss: 0.4493 - val_accuracy: 0.8515

In [ ]:
model.save("model.h5")

In [ ]:
y_pred = model.predict(embedded_test_x)
y_pred

250/250 [==============================] - 19s 77ms/step


array([[0.12542339, 0.5886645 , 0.31128687, 0.908932  , 0.8769034 ],
       [0.03453974, 0.00184798, 0.9975694 , 0.7455028 , 0.41267216],
       [0.18652321, 0.54786676, 0.2669394 , 0.98746204, 0.3746348 ],
       ...,
       [0.1407244 , 0.00821428, 0.99771535, 0.1768557 , 0.28943947],
       [0.06086601, 0.20009752, 0.619383  , 0.999402  , 0.09322514],
       [0.36407307, 0.3246183 , 0.25206545, 0.1372863 , 0.99124235]],
      dtype=float32)

In [ ]:
test_y.shape, y_pred.shape

((8000, 5), (8000, 5))

In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score
accuracy_score(np.argmax(test_y,1),np.argmax(y_pred,1))

0.856625

In [ ]:
embed_vect = 40
model1 = Sequential()
model1.add(Embedding(5000,embed_vect,input_length=40))
model1.add(Dropout(0.3))
model1.add(LSTM(150))
model1.add(Dropout(0.3))
model1.add(Dense(5,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
model1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 40, 40)            200000    
                                                                 
 dropout_2 (Dropout)         (None, 40, 40)            0         
                                                                 
 lstm_1 (LSTM)               (None, 150)               114600    
                                                                 
 dropout_3 (Dropout)         (None, 150)               0         
                                                                 
 dense_1 (Dense)             (None, 5)                 755       
                                                                 
Total params: 315,355
Trainable params: 315,355
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model1.fit(embedded_train_x,train_y,epochs=10,batch_size=128,validation_data=(embedded_test_x,test_y))

Epoch 1/10
94/94 [==============================] - 26s 245ms/step - loss: 0.4668 - accuracy: 0.4073 - val_loss: 0.4379 - val_accuracy: 0.4181
Epoch 2/10
94/94 [==============================] - 22s 239ms/step - loss: 0.4089 - accuracy: 0.5019 - val_loss: 0.3647 - val_accuracy: 0.5984
Epoch 3/10
94/94 [==============================] - 29s 305ms/step - loss: 0.2940 - accuracy: 0.6675 - val_loss: 0.2653 - val_accuracy: 0.7231
Epoch 4/10
94/94 [==============================] - 22s 237ms/step - loss: 0.2085 - accuracy: 0.7757 - val_loss: 0.2366 - val_accuracy: 0.7465
Epoch 5/10
94/94 [==============================] - 22s 235ms/step - loss: 0.1726 - accuracy: 0.8295 - val_loss: 0.2146 - val_accuracy: 0.7996
Epoch 6/10
94/94 [==============================] - 24s 252ms/step - loss: 0.1297 - accuracy: 0.8819 - val_loss: 0.1790 - val_accuracy: 0.8286
Epoch 7/10
94/94 [==============================] - 23s 242ms/step - loss: 0.1016 - accuracy: 0.9059 - val_loss: 0.1831 - val_accuracy: 0.8365

In [ ]:
model1.save("model1.h5")

In [ ]:
embedded_test_x.shape, test_y.shape, embedded_train_x.shape, 

((8000, 40), (8000, 5), (12000, 40))

In [ ]:
y_pred1 = model1.predict(embedded_test_x)

250/250 [==============================] - 7s 25ms/step


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(np.argmax(test_y,1),np.argmax(y_pred1,1))

0.86075

In [ ]:
import tensorflow as tf
model2 = tf.keras.Sequential([
    tf.keras.layers.Embedding(5000,embed_vect,input_length=40),
    tf.keras.layers.Bidirectional(tf.keras.layers.GRU(32)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(5, activation='sigmoid'),
])
model2.compile(loss='binary_crossentropy',optimizer='adam',metrics='accuracy')
model2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 40, 40)            200000    
                                                                 
 bidirectional_1 (Bidirectio  (None, 64)               14208     
 nal)                                                            
                                                                 
 dense_2 (Dense)             (None, 10)                650       
                                                                 
 dense_3 (Dense)             (None, 10)                110       
                                                                 
 dense_4 (Dense)             (None, 10)                110       
                                                                 
 dense_5 (Dense)             (None, 10)                110       
                                                      

In [ ]:
model2.fit(embedded_train_x,train_y,epochs=20,batch_size=128,validation_data=(embedded_test_x,test_y))

Epoch 1/20
94/94 [==============================] - 17s 104ms/step - loss: 0.6663 - accuracy: 0.1343 - val_loss: 0.6198 - val_accuracy: 0.1395
Epoch 2/20
94/94 [==============================] - 7s 74ms/step - loss: 0.5727 - accuracy: 0.2608 - val_loss: 0.5409 - val_accuracy: 0.3121
Epoch 3/20
94/94 [==============================] - 9s 92ms/step - loss: 0.4988 - accuracy: 0.4238 - val_loss: 0.4850 - val_accuracy: 0.5210
Epoch 4/20
94/94 [==============================] - 7s 74ms/step - loss: 0.4352 - accuracy: 0.5596 - val_loss: 0.4294 - val_accuracy: 0.4320
Epoch 5/20
94/94 [==============================] - 8s 90ms/step - loss: 0.3741 - accuracy: 0.5003 - val_loss: 0.3813 - val_accuracy: 0.5669
Epoch 6/20
94/94 [==============================] - 8s 87ms/step - loss: 0.3173 - accuracy: 0.6497 - val_loss: 0.3439 - val_accuracy: 0.6564
Epoch 7/20
94/94 [==============================] - 7s 77ms/step - loss: 0.2782 - accuracy: 0.7198 - val_loss: 0.3377 - val_accuracy: 0.6518
Epoch 8/20


In [ ]:
model2.save("model2.h5")

In [ ]:
y_pred2 = model2.predict(embedded_test_x)

250/250 [==============================] - 3s 9ms/step


In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score
accuracy_score(np.argmax(test_y,1),np.argmax(y_pred2,1))

0.795375

In [ ]:
import numpy
y_final1 = []
for counter,i in enumerate(zip(y_pred,y_pred1,y_pred2)):
  y_new1 = []
  for j,h,z in zip(i[0],i[1],i[2]):
    y_new1.append(max([j,h,z]))
  y_final1.append(y_new1)

for counter,i in enumerate(y_final1):
  max_value1 = numpy.argmax(i)
  y_final1[counter] = [1 if x==max_value1 else 0 for x,z in enumerate(i)]

y_final1

[[0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1],
 [0, 0, 0,

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(np.argmax(test_y,1),np.argmax(y_final1,1))

0.86425

In [ ]:
user_message = "Everyone is avoiding me i am not aware that how can i hope on to work with them. They are not even talking to me which makes me a bit more worried."

In [ ]:
stringo = user_message.lower() 

In [ ]:
resulto = " "
for i in stringo.split():
  if i not in stopper:
    resulto=resulto+i+" "
resulto = resulto.strip()

In [ ]:
resulto

'everyone avoiding aware hope work them. even talking makes bit worried.'

In [ ]:
new_sento = ""
for i in  resulto.split(" "):
  new_sento = new_sento+lemmatizer.lemmatize(i)+" "

In [ ]:
x_rep_o = [one_hot(new_sento,5000)]

In [ ]:
sent_length = 40
embedded_x_o = pad_sequences(x_rep_o,padding='pre',maxlen=sent_length)

In [ ]:
loaded_model = tf.keras.models.load_model('model.h5')
loaded_model1 = tf.keras.models.load_model('model1.h5')
loaded_model2 = tf.keras.models.load_model('model2.h5')

In [ ]:
ypredo = loaded_model.predict(embedded_x_o)
ypredo1 = loaded_model1.predict(embedded_x_o)
ypredo2 = loaded_model2.predict(embedded_x_o)

1/1 [==============================] - 0s 41ms/step


In [ ]:
print(ypredo,
ypredo1,
ypredo2,)

[[0.14922944 0.63359654 0.46439943 0.9807099  0.29330122]] [[0.02800571 0.49864915 0.0129452  0.40409312 0.00766416]] [[0.02800571 0.49864915 0.0129452  0.40409312 0.00766416]]


In [ ]:
import numpy
y_final1o = []
for counter,i in enumerate(zip(ypredo,ypredo1,ypredo2)):
  y_new1o = []
  for j,h,z in zip(i[0],i[1],i[2]):
    y_new1o.append(max([j,h,z]))
  y_final1o.append(y_new1o)

y_final1o
for counter,i in enumerate(y_final1o):
  max_value1 = numpy.argmax(i)
  y_final1o[counter] = [1 if x==max_value1 else 0 for x,z in enumerate(i)]

y_final1o

[[0.14922944, 0.63359654, 0.46439943, 0.9807099, 0.29330122]]

[[0, 0, 0, 1, 0]]

In [ ]:
np.argmax(y_final1o,1)

array([3])